// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtP9rtSgpjNTjLqYTcmpqZgG3N-g944JU',
    appId: '1:590945707402:web:988f259be3c9235be99473',
    messagingSenderId: '590945707402',
    projectId: 'flutter-ad8a0',
    authDomain: 'flutter-ad8a0.firebaseapp.com',
    storageBucket: 'flutter-ad8a0.firebasestorage.app',
    measurementId: 'G-ELXPP7DHXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ChpU_TM_I4fqV1GSrasXPJMxH5okeWY',
    appId: '1:590945707402:android:6f41a87ae7dac5ebe99473',
    messagingSenderId: '590945707402',
    projectId: 'flutter-ad8a0',
    storageBucket: 'flutter-ad8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jEk3Vuqvrb7f3tEwSWkonf_KW7_YW2o',
    appId: '1:590945707402:ios:766e0a445a76eb6de99473',
    messagingSenderId: '590945707402',
    projectId: 'flutter-ad8a0',
    storageBucket: 'flutter-ad8a0.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jEk3Vuqvrb7f3tEwSWkonf_KW7_YW2o',
    appId: '1:590945707402:ios:766e0a445a76eb6de99473',
    messagingSenderId: '590945707402',
    projectId: 'flutter-ad8a0',
    storageBucket: 'flutter-ad8a0.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtP9rtSgpjNTjLqYTcmpqZgG3N-g944JU',
    appId: '1:590945707402:web:21ce10023d56bac2e99473',
    messagingSenderId: '590945707402',
    projectId: 'flutter-ad8a0',
    authDomain: 'flutter-ad8a0.firebaseapp.com',
    storageBucket: 'flutter-ad8a0.firebasestorage.app',
    measurementId: 'G-XJQB516JR5',
  );
}
